import { chromium } from "playwright";
const KNOWN=/valid external Instance reference no longer exists/i;
const b=await chromium.launch({executablePath:"/opt/pw-browsers/chromium",args:["--enable-unsafe-webgpu","--enable-features=Vulkan","--use-angle=vulkan","--use-vulkan=swiftshader","--no-sandbox"]});
const p=await b.newPage();const e=[];p.on("pageerror",x=>e.push(x.message));p.on("console",m=>{if(m.type()==="error")e.push(m.text())});
await p.goto("file:///home/claude/zigverse/dist/Environment_v0.6_vitrine.html#world=tidepool&stage=soft");
await p.waitForTimeout(3000);
const agit=async()=>{const t=await p.evaluate(()=>(document.getElementById("hud")||{}).innerText||"");const m=t.match(/agit ([0-9.]+)/);return m?m[1]:"?";};
const start=await agit();
await p.keyboard.press("Semicolon"); await p.waitForTimeout(500); const a1=await agit();
await p.keyboard.press("Semicolon"); await p.waitForTimeout(500); const a2=await agit();
await p.keyboard.press("Semicolon"); await p.waitForTimeout(500); const a3=await agit();
await p.keyboard.press("Quote");     await p.waitForTimeout(500); const q1=await agit();
await p.keyboard.press("Quote");     await p.waitForTimeout(500); const q2=await agit();
const live=await p.evaluate(()=>/fps/.test((document.getElementById("status")||{}).textContent||""));
console.log("start:",start," after ;;; :",a1,a2,a3," after '' :",q1,q2);
console.log("live:",live," hard errors:",e.filter(x=>!KNOWN.test(x)).length);
const ok = start==="1.0" && a3==="0.7" && q2==="0.9" && live;
console.log(ok?"AGIT VERIFY: PASS (1.0 →;;;→ 0.7 →''→ 0.9)":"AGIT VERIFY: unexpected values");
await b.close();
