import { chromium } from "playwright";
const KNOWN=/valid external Instance reference no longer exists/i;
const b=await chromium.launch({executablePath:"/opt/pw-browsers/chromium",args:["--enable-unsafe-webgpu","--enable-features=Vulkan","--use-angle=vulkan","--use-vulkan=swiftshader","--no-sandbox"]});
const p=await b.newPage();const e=[];p.on("pageerror",x=>e.push(x.message));p.on("console",m=>{if(m.type()==="error")e.push(m.text())});
await p.goto("file:///home/claude/zigverse/dist/Environment_v0.3_current.html#cur=gyre&force=sink&med=honey");
await p.waitForTimeout(3000);
const s=await p.evaluate(()=>({c:window.ZIG_CURRENT,st:(document.getElementById("status")||{}).textContent||""}));
const hard=e.filter(x=>!KNOWN.test(x));
console.log("bundle status:",JSON.stringify(s.st.slice(0,70)),"cur:",s.c,"hard:",hard.length);hard.slice(0,2).forEach(x=>console.log("  ",x.slice(0,160)));
await b.close();process.exit(hard.length===0 && /fps/.test(s.st)?0:1);
