#!/usr/bin/env node
/* =============================================================================
   tools/apply_land_relay024.mjs — THE RECORD FOR RELAY 0.23 / 0.24
   run:  node tools\\apply_land_relay024.mjs

   Appends one entry to briefs/Session_Log.md, covering:
     · 0.23 - the live lag from note-change interval, the Pacemaker correction,
       and THE CATCH-UP with its measured numbers.
     · the EWI scope and tools/serve.mjs (Web MIDI needs a secure context).
     · 0.24 - no minimum breath. The dead zone Bill found by playing, the
       arithmetic behind it, and the principle: a supply point must not leak.

   APPEND ONLY. It checks the file still ends where it expected before writing a
   byte, so it cannot clobber an entry added from another machine, and running it
   twice is a no-op rather than a duplicate.

   CANON.md is deliberately NOT touched. Section 4 is the post-summit CANDIDATE
   ledger and Relay was never one of those ten; the law's real registration is
   the `relay` entry in ZigCore.Canon.laws, which shipped inside zigcore.js.
   ========================================================================== */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";

const CANDIDATES = [
  path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."),
  process.cwd()
];
const looksRight = (d) => existsSync(path.join(d, "engine", "zigcore.js")) &&
                          existsSync(path.join(d, "briefs", "Session_Log.md"));
const ROOT = CANDIDATES.find(looksRight);
if (!ROOT) {
  console.log("\n  CANNOT LOCATE THE REPO. Tried:");
  CANDIDATES.forEach((d) => console.log("    " + d));
  console.log("  Run this from C:\\Users\\billy\\Zigverse - nothing was written.\n");
  process.exit(1);
}

const LOG    = path.join(ROOT, "briefs", "Session_Log.md");
const ENTRY  = Buffer.from("Ci0tLQoKIyMgMjAyNi0wOS0wOSDCtyBPcHVzLUdseXBoIMK3IFJFTEFZIDAuMjMgLyAwLjI0IOKAlCB0aGUgbGFnIGxlYXJucyB0aGUgdGVtcG8sIGFuZCB0aGUgd2FsbCBjb21lcyBkb3duCgpDb250aW51ZXMgdGhlIDAuMjIgc2Vzc2lvbi4gQmFzZSB3YXMgYDVkNDg3ZmJgLCB0YWdnZWQgKipgcmVsYXkvMC4yMmAqKi4KCiMjIyAwLjIzIOKAlCBUSEUgTElWRSBMQUcsIGRyaXZlbiBieSB0aGUgcmF0ZSBvZiBOT1RFIENIQU5HRQoKQmlsbDogKiJ0aGUgdGVsZW1ldHJ5IHRoYXQgZml0cyBteSBwbGF5aW5n4oCmIG5vdCB0b25ndWluZyBvciBicmVhdGhpbmcsIGp1c3QgdGhlIGV4YWN0IHRpbWUgZWFjaApub3RlIGNoYW5nZXMgdG8gdGhlIG5leHQuIioKCioqQSBjb3JyZWN0aW9uIHRvIHdoYXQgSSBjbGFpbWVkIGF0IHRoZSBlbmQgb2YgdGhlIDAuMjIgc2Vzc2lvbi4qKiBJIHNhaWQgUGFjZW1ha2VyIGFscmVhZHkKbWVhc3VyZWQgdGhpcy4gSXQgZG9lcyBub3QuIFJlYWRpbmcgdGhlIHNvdXJjZSBwcm9wZXJseTogaXRzIFBMTCBhY2NlcHRzIG9ubHkgb25zZXRzIHRoYXQgRk9MTE9XClNJTEVOQ0UgKGdhcCA+IGByaWJib25HYXBgIDAuMzVzKSDigJQgaXRzIG93biBoZWFkZXIgc2F5cyAqInRoZSBwdWxzZSBsaXZlcyBpbiB0aGUgZ2Fwcywgbm90IHRoZQpub3Rlcy4iKiBUaGUgZmFzdCBub3RlcyBpbnNpZGUgb25lIG9mIEJpbGwncyByaWJib25zIG5ldmVyIHJlYWNoIGBwZXJpb2RgIGF0IGFsbDsgdGhleSBvbmx5IHJhaXNlCmBmbG93YC4gU28gYHBlcmlvZGAgaXMgdGhlIFBIUkFTRSBwdWxzZSwgYW5kIG5vdGUtdG8tbm90ZSB0aW1lIGlzIGV4YWN0bHkgdGhlIHRoaW5nIFBhY2VtYWtlcgpkZWxpYmVyYXRlbHkgZGlzY2FyZHMuIFRoZSBgcmF0aW8gMC4yMjdgIGNhbGlicmF0aW9uIGJ1aWx0IG9uIGl0IHdhcyBzY3JhcHBlZC4KClJlbGF5IHRoZXJlZm9yZSBtZWFzdXJlcyB0aGUgaW50ZXJ2YWwgaXRzZWxmIOKAlCBvbmUgc3VidHJhY3Rpb24gaW4gYG5vdGUoKWAsIG5vdCBhIHNlY29uZCBlc3RpbWF0b3IuCgotICoqYHJhdGlvYCoqLCBkZWZhdWx0ICoqMSoqOiBsYWcgSVMgdGhlIGludGVydmFsLiBPbmUgaG9wIHBlciBub3RlLiBUaGUgYm9keSdzIGNvbmR1Y3Rpb24gc3BlZWQKICBlcXVhbHMgdGhlIG5vdGUgcmF0ZSwgYW5kIHRoZSB3YXZlIGJlY29tZXMgYSBtb3ZpbmcgcmVjb3JkIG9mIHJvdWdobHkgdGhlIGxhc3QgKm4qIG5vdGVzIHBsYXllZC4KICBVbmRlciB0aGlzIHNjaGVtZSBCaWxsJ3MganVkZ2VkIDAuMTcgaXMgbm90IGEgY29uc3RhbnQg4oCUIGl0IGlzIHNpbXBseSB0aGUgdGVtcG8gaXQgY29ycmVzcG9uZHMgdG8uCi0gKipgc25hcGAqKiAwLi4xIOKAlCBibGVuZCBmcm9tIHJhdyBub3RlIGludGVydmFsIHRvd2FyZCBQYWNlbWFrZXIncyBwaHJhc2UgcHVsc2UuIFR3byBnZW51aW5lbHkKICBkaWZmZXJlbnQgY3JlYXR1cmVzLCBvbmUgbGF3LiBMZWZ0IGFzIGEgbGl2ZSBkaWFsIHJhdGhlciB0aGFuIGEgY2hvc2VuIGRlZmF1bHQuCi0gKipgbGFnTWluYCAvIGBsYWdNYXhgKiogKDAuMDMgLyAwLjYwKSDigJQgYSB0cmlsbCBjYW5ub3QgY29sbGFwc2UgdGhlIGJvZHksIGEgaGVsZCBub3RlIGNhbm5vdAogIHN0YWxsIGl0LiBBIGhlbGQgbm90ZSBtYWtlcyBubyBjYWxsIGF0IGFsbCwgc28gdGhlIGJvZHkga2VlcHMgdGhlIHRlbXBvIG9mIHRoZSBsYXN0IHRyYW5zaXRpb24uCi0gUGVyLXN0YWdlICoqYHNoYXBlYCoqIGtlcHQgYXMgcmF0aW9zLCBzbyBhIHRhcGVyZWQgYm9keSAoc3RpZmYgbmVjaywgbG9vc2UgdGFpbCkgcmVzY2FsZXMgdGhyb3VnaAogIGEgdGVtcG8gY2hhbmdlIGluc3RlYWQgb2YgZmxhdHRlbmluZyB0byB1bmlmb3JtLgoKKipUSEUgQ0FUQ0gtVVAg4oCUIGVtZXJnZW50LCBub2JvZHkgd3JvdGUgaXQuKiogTGFnIGlzIHJlYWQgYXQgZXhhY3RseSBvbmUgbW9tZW50OiB3aGVuIGEgc3RhZ2UKc2NoZWR1bGVzIHRoZSBuZXh0LiBBIGRlbGl2ZXJ5IGFscmVhZHkgdHJhdmVsbGluZyBrZWVwcyB0aGUgbGFnIGl0IGxhdW5jaGVkIHdpdGguIFR3byB3YXZlcwpsYXVuY2hlZCAqKjAuNTBzIGFwYXJ0KiosIG1lYXN1cmVkIGF0IHRoZSB0YWlsOgoKfCAybmQgbm90ZSBpbnRlcnZhbCB8IGFycml2YWxzIGFwYXJ0IHwKfC0tLXwtLS18CnwgMC4wOHMgfCAqKjAuMTRzKiogfAp8IDAuMTVzIHwgMC4yOXMgfAp8IDAuMjVzIChubyBjaGFuZ2UpIHwgMC40OXMgfAp8IDAuNDVzIHwgKiowLjg4cyoqIHwKCkFjY2VsZXJhdGUgYW5kIHRoZSBib2R5IGNvbXByZXNzZXMgdG8gdW5kZXIgYSB0aGlyZCBvZiB0aGUgbGF1bmNoIGdhcDsgZGVjZWxlcmF0ZSBhbmQgaXQgc3ByZWFkcyB0bwpuZWFybHkgZG91YmxlLiAqKlRoaXMgZXhpc3RzIG9ubHkgYmVjYXVzZSB0aGUgZHJpdmVyIGlzIHBlci1FVkVOVC4qKiBBIGNvbnRpbnVvdXMgZHJpdmVyIChicmVhdGgpCndvdWxkIGdpdmUgZXZlcnkgd2F2ZSBpbiBmbGlnaHQgdGhlIHNhbWUgc3BlZWQgYW5kIGRlc3Ryb3kgaXQuIFRoYXQgaXMgdGhlIGFyZ3VtZW50IGZvciBub3RlCmNoYW5nZXMgb3ZlciBicmVhdGgsIHN0YXRlZCBhcyBhIG51bWJlciByYXRoZXIgdGhhbiBhIHByZWZlcmVuY2UuCgojIyMgVEhFIFNDT1BFIEdFVFMgVEhFIEVXSQoKYHRvb2xzL3JlbGF5X3Njb3BlLmh0bWxgIOKAlCBXZWIgTUlESS4gTm90ZS1vbiA9IGEgbm90ZSBjaGFuZ2UgKGRyaXZlcyB0aGUgbGFnIEFORCBmZWVkcwpgUGFjZW1ha2VyLm5vdGVPbmAsIHNvIGBzbmFwYCBibGVuZHMgdG93YXJkIGEgcmVhbCBwdWxzZSk7IENDMiA9IHRoZSBzdXBwbHkgaW50byB0aGUgaGVhZDsgbGl2ZQpyZWFkb3V0IG9mIFBhY2VtYWtlciBgcGVyaW9kYCAvIGBjb25maWRlbmNlYCAvIGBmbG93YC4KCmB0b29scy9zZXJ2ZS5tanNgIOKAlCBORVcsIGRlcGVuZGVuY3ktZnJlZSBsb2NhbCBzZXJ2ZXIuICoqV2ViIE1JREkgaXMgb25seSBncmFudGVkIG9uIGEgU0VDVVJFCkNPTlRFWFQuKiogT3BlbmVkIGFzIGBmaWxlOi8vYCB0aGUgcGFnZSBjYW4gbmV2ZXIgc2VlIHRoZSBFV0k6IG5vIHByb21wdCwgbm8gZXJyb3IsIGp1c3Qgc2lsZW5jZS4KYGh0dHA6Ly9sb2NhbGhvc3RgIGlzIGEgc2VjdXJlIGNvbnRleHQuIFRoZSBzYW1lIHRyYXAgd2FzIG1ldCBmcm9tIHRoZSBvdGhlciBzaWRlIHdoZW4gUGFnZXMgYmVjYW1lCnRoZSByb3V0ZSBmb3IgdGhlIEJlZSdzIE1JREkgcGVybWlzc2lvbjsgdGhpcyBpcyB0aGUgbG9jYWwgdmVyc2lvbiwgbm8gcHVzaCByZXF1aXJlZC4KCiMjIyAwLjI0IOKAlCBOTyBNSU5JTVVNIEJSRUFUSC4gRm91bmQgYnkgcGxheWluZy4KCkJpbGwsIGZpcnN0IHNlc3Npb24gb24gdGhlIEVXSTogKiJXaGF0IEkgZG9uJ3QgbGlrZSBpcyBoYXZpbmcgdG8gaGl0IGEgbWluaW11bSB0aHJlc2hvbGQgb24gYnJlYXRoCnRvIGFjdGl2YXRlIGl0LiIqCgoqKkl0IHdhcyBhcml0aG1ldGljLCBub3QgdGFzdGUuKiogVGhlIGhlYWQgZmlsbGVkIGF0IGBnIMOXIGJyZWF0aGAgYW5kIGJsZWQgYXQgYSBjb25zdGFudCBgYmAuIE5ldAphY2N1bXVsYXRpb24gaXMgemVybyBhdCBgYnJlYXRoID0gYi9nYCDigJQgYW5kIGJlbG93IHRoYXQgdGhlIGhlYWQgY2FuIE5FVkVSIHJlYWNoIHRocmVzaG9sZCwgaG93ZXZlcgpsb25nIGl0IGlzIGhlbGQuIE5vdCBzbG93OiAqKmltcG9zc2libGUqKi4gV2l0aCB0aGUgc2NvcGUncyAxLjYgYW5kIDAuMzUgdGhlIHdhbGwgc2F0IGF0ICoqMC4yMTkqKiwKa2lsbGluZyBCaWxsJ3MgZW50aXJlIHNvZnQgcmFuZ2UsIGFuZCAwLjI14oCTMC4zNSB3YXMgc28gc2xvdyAoNy43cyB0byBmaXJzdCBldmVudCkgaXQgbWF5IGFzIHdlbGwKaGF2ZSBiZWVuIGRlYWQgdG9vLgoKKipUSEUgUFJJTkNJUExFOiB0aGUgc3VwcGx5IHBvaW50IG11c3Qgbm90IGxlYWssIG9yIHRoZSBpbnN0cnVtZW50IGFjcXVpcmVzIGEgbWluaW11bS4qKiBCbGVlZApleGlzdHMgc28gdGhlIGJvZHkgZGVjb21wcmVzc2VzIHdoZW4gdGhlIHBlcmZvcm1lciBzdG9wcy4gQnV0IHN0YWdlIDAgaXMgd2hlcmUgYnJlYXRoIEVOVEVSUywgYW5kCmRyYWluaW5nIHRoZSBlbnRyeSBwb2ludCBpcyBwcmVjaXNlbHkgd2hhdCB0dXJucyBhbiBpbnN0cnVtZW50IGludG8gYSBzd2l0Y2guCgpGaXg6ICoqYGhlYWRCbGVlZGAsIGRlZmF1bHQgMCoqIOKAlCB0aGUgaGVhZCBpcyBhbiBpbnRlZ3JhdG9yLiBEb3duc3RyZWFtIHN0YWdlcyBsZWFrIGV4YWN0bHkgYXMKYmVmb3JlLCBzbyBmb2xsb3ctdGhyb3VnaCBhbmQgcmVzdCBhcmUgdW5jaGFuZ2VkLiBPbmUgY29uZGl0aW9uYWwsIG5vIHNoYWRlciBwYXRoLgoKV2l0aCBicmVhdGggZ2FpbiA4OiBicmVhdGggMC4wMyBzcGVha3MgaW4gNC4ycywgMC4xMCBpbiAxLjNzLCAwLjIwIGluIDAuNnMsIDEuMDAgaW4gMC4xM3MuICoqTm8KZmxvb3IsIG9ubHkgcGF0aWVuY2UqKiDigJQgYW5kIHRoZSBvcmRlciBpcyBwcmVzZXJ2ZWQsIGhhcmRlciBhbHdheXMgc3BlYWtzIHNvb25lci4gQXQgdGhlIHRvcCB0aGUKZXNjYXBlbWVudCdzIG93biBgc3BpbGxgIGNhcHMgdGhlIHJhdGUgYXQgfjMuNi9zLCBzbyBoYXJkIGJsb3dpbmcgc2F0dXJhdGVzIGludG8gYSBzdHJlYW0gcmF0aGVyCnRoYW4gYSBtYWNoaW5lIGd1bi4gVGhhdCBjZWlsaW5nIGNhbWUgZnJlZSBmcm9tIGEgbGF3IGFscmVhZHkgcHJlc2VudC4KClRoZSBmYXVsdCBpcyBwcmVzZXJ2ZWQgaW4gYHZlcnRlYnJhX3JlZmAgYXMgYW4gYXNzZXJ0aW9uIOKAlCBhIGxlYWtpbmcgaGVhZCBpcyBwcm92ZW4gdG8gbWFrZSBicmVhdGgKMC4xNSAqbmV2ZXIqIHNwZWFrIOKAlCBzbyBpdCBjYW5ub3QgY29tZSBiYWNrIHVubm90aWNlZC4KCioqQmlsbCdzIHZlcmRpY3Qgb24gMC4yNDogIlRoaXMgaXMgYSBuZXcgbGV2ZWwgb2YgcmVzcG9uc2UuIioqIE5vdCB5ZXQgdGFnZ2VkOyBtb3JlIHBsYXlpbmcgZmlyc3QuCgojIyMgRmluZGluZ3MgdGhhdCBvdXRsaXZlIFJlbGF5CgotICoqQSBzdXBwbHkgcG9pbnQgbXVzdCBub3QgbGVhay4qKiBBbnkgYWNjdW11bGF0ZS10aGVuLXRyaXAgbWVjaGFuaXNtIGZlZCBieSBhIGNvbnRpbnVvdXMgc291cmNlCiAgYWNxdWlyZXMgYSBoYXJkIG1pbmltdW0gYXQgYGxlYWsvZ2FpbmAgaWYgdGhlIGFjY3VtdWxhdG9yIGlzIGRyYWluZWQuICoqV29ydGggYXVkaXRpbmcgZWxzZXdoZXJlCiAgaW4gdGhlIGVuZ2luZSDigJQgY2hhcmlzbWEgZHdlbGwgaXMgdGhlIG9idmlvdXMgY2FuZGlkYXRlKiosIHNpbmNlIGl0IGFjY3VtdWxhdGVzLCBoYXMgYSByZWxlYXNlLAogIGFuZCB0aGUgQmVlIGhhcyBhIGxvbmcgaGlzdG9yeSBvZiBhcHBlYXJpbmcgaW5lcnQuCi0gKipBIHN0b3JlIHRoYXQgbGVha3MgY2Fubm90IGFsc28gY291bnQqKiAoZnJvbSAwLjIyLCByZWNvbmZpcm1lZCk6IGdlYXJpbmcgbmVlZHMgY2hhcmdlIHRvIHN1cnZpdmUKICBiZXR3ZWVuIGRlbGl2ZXJpZXMuIFBlciBzdGFnZSwgYSBib2R5IGlzIGEgY291bnRpbmcgc3BpbmUgb3IgYSBicmVhdGhpbmcgb25lLgotICoqUGVyLWV2ZW50IGRyaXZlcnMgcHJvZHVjZSBiZWhhdmlvdXIgY29udGludW91cyBkcml2ZXJzIGNhbm5vdC4qKiBBbnkgcGFyYW1ldGVyIHJlYWQgYXQgYQogIGRpc2NyZXRlIG1vbWVudCByYXRoZXIgdGhhbiBldmVyeSBmcmFtZSBoYXMgdGhlIGNhdGNoLXVwIHByb3BlcnR5IGF2YWlsYWJsZS4gR2VuZXJhbCB0ZWNobmlxdWUuCgoqKkNoYW5nZWQ6KiogYGVuZ2luZS96aWdjb3JlLmpzYCAoUmVsYXkgMC4yMiDihpIgMC4yNCkgwrcgYHRvb2xzL3JlbGF5X3Njb3BlLmh0bWxgIMK3IGBicmllZnMvU2Vzc2lvbl9Mb2cubWRgCioqQWRkZWQ6KiogYHRvb2xzL3NlcnZlLm1qc2AgwrcgYHRvb2xzL2FwcGx5X3JlbGF5MDIzLm1qc2AgwrcgYHRvb2xzL2FwcGx5X2V3aV9zY29wZS5tanNgIMK3IGB0b29scy9hcHBseV9yZWxheTAyNC5tanNgCioqUGFzc2VkOioqIGBub2RlIC0tY2hlY2tgIGNsZWFuICg0IGZpbGVzKSDCtyByZWZlcmVuY2UgZ2F0ZSAqKjQzLzQzKiosIGB2ZXJ0ZWJyYV9yZWZgIG5vdyAzNyBjaGVja3MgwrcKYnl0ZS1pZGVudGl0eSAqKjUvNSBJREVOVElDQUwqKiDCtyBpbnN0YWxsZXIgc2VsZi12ZXJpZnkgMy8zIHNoYTI1NiBPSyBvbiBleWVaIMK3IE1ldGFsIGdhdGUgKipub3QgcnVuKiosCioqbm90IHJlcXVpcmVkKiog4oCUIG5vIFdHU0wgY2hhbmdlZC4KCioqT3BlbjoqKiB0YWcgYHJlbGF5LzAuMjRgIG9uY2UgQmlsbCBoYXMgcGxheWVkIGl0IHByb3Blcmx5IMK3IGBzbmFwYCBkZWZhdWx0IHN0aWxsIHVuY2hvc2VuIMK3CmBicmVhdGggZ2FpbmAgaXMgYSBzY29wZSBkaWFsIGF0IDgsIG5vdCB5ZXQgYSBqdWRnZWQgbnVtYmVyIMK3ICoqbm8gVmVydGVicmEgc3BlY2ltZW4qKiDigJQgUmVsYXkgbmVlZHMKYW4gT1JERVIgYW5kIHRoZSBlbmdpbmUncyBhZ2VudHMgYXJlIGEgZmllbGQgd2l0aCBubyBpbmRleDsgdGhlIHRocmVlIGNhbmRpZGF0ZXMgYXJlIHNwYXRpYWwgYmFuZHMsCmBFbnYuYm9uZHNgIHRvcG9sb2d5LCBvciBgbGlmZUhhc2hgIGdyb3VwcywgYW5kIHRoYXQgaXMgYSBkZXNpZ24gY2FsbCBmb3IgQmlsbCDCtyB0aGUgZHJhd24tbWVtYnJhbmUKcHJpbWl0aXZlIGZvciBHaWxsL0FsdmVvbHVzLCBzdGlsbCB1bmJ1aWx0IGFuZCBzdGlsbCB0aGUgZXhwZW5zaXZlIGl0ZW0gwrcgYSBuYW1lZCBkZWZlY3Qgc2xvdCBvbgpgWklHQUdFYCDCtyBgWmlnV2ViR1BVLlZFUlNJT05gIHN0aWxsIDAuNDYuMC4KCiMjIyBBbiBpbnN0YWxsZXIgZmF1bHQgd29ydGgga2VlcGluZwoKVGhlIGZpcnN0IGBhcHBseV92ZXJ0ZWJyYS5tanNgIHJlc29sdmVkIGl0cyByb290IHdpdGggYG5ldyBVUkwoaW1wb3J0Lm1ldGEudXJsKS5wYXRobmFtZWAuIE9uCldpbmRvd3MgdGhhdCB5aWVsZHMgYC9DOi9Vc2Vycy8uLi5gIGFuZCBqb2luaW5nIHByb2R1Y2VzIGBDOlxDOlxVc2Vyc1wuLi5gLiBJdCBwYXNzZWQgb24gdGhlIExpbnV4CmNvbnRhaW5lciBhbmQgKipjb3VsZCBub3QqKiBwYXNzIG9uIGV5ZVouIEZpeGVkIHdpdGggYGZpbGVVUkxUb1BhdGhgLCB0aGVuIG1hZGUgc3RydWN0dXJhbDogZXZlcnkKaW5zdGFsbGVyIHNpbmNlICoqcHJvdmVzIGl0cyByb290Kiog4oCUIGFjY2VwdGluZyBhIGNhbmRpZGF0ZSBvbmx5IGlmIGBlbmdpbmUvemlnY29yZS5qc2AsIGB0ZXN0L2AgYW5kCmB0b29scy9gIGFyZSBhY3R1YWxseSB0aGVyZSwgYW5kIHJlZnVzaW5nIHRvIHdyaXRlIGF0IGFsbCBvdGhlcndpc2UuCgoqVGhlIG1hY2hpbmUgdGhhdCB0ZXN0cyBpcyBub3QgdGhlIG1hY2hpbmUgdGhhdCBydW5zLiogU2FtZSBzaGFwZSBhcyB0aGUgTWV0YWwgbGVzc29uLgo=", "base64");
const ANCHOR = Buffer.from("J3Mgc21vb3RoZWQgYHBlcmlvZGAgKHRoZSBib2R5IGxlYXJucyB0aGUgdGVtcG87IG9ybmFtZW50cyBkb24ndCBkaXN0dXJiCml0KS4gVG8gYmUgYnVpbHQgYXMgYSBgc25hcGAgYmxlbmQga25vYiBzbyBpdCBpcyBqdWRnZWQgbGl2ZSByYXRoZXIgdGhhbiBjaG9zZW4gYmxpbmQuCg==", "base64");
const WANT_SHA = "2cb5fdae8df29ee6";
const sha = (b) => createHash("sha256").update(b).digest("hex").slice(0, 16);

console.log("\n  ZIGVERSE - landing the record for RELAY 0.23 / 0.24\n  root: " + ROOT + "\n");

const cur = readFileSync(LOG);
if (cur.includes(ENTRY)) {
  console.log("  ALREADY PRESENT  briefs/Session_Log.md - nothing to do.\n");
  process.exit(0);
}
if (!cur.subarray(-ANCHOR.length).equals(ANCHOR)) {
  console.log("  REFUSING TO WRITE. briefs/Session_Log.md does not end where expected -");
  console.log("  something was appended since this installer was built. Nothing written;");
  console.log("  send this to Glyph and the entry will be rebuilt against the current file.\n");
  process.exit(1);
}

const next = Buffer.concat([cur, ENTRY]);
writeFileSync(LOG, next);
const back = readFileSync(LOG);
if (back.length === next.length && sha(back) === WANT_SHA) {
  console.log("  APPENDED   briefs/Session_Log.md   " + cur.length + " -> " + back.length +
              " bytes  (+" + ENTRY.length + ") . sha " + sha(back) + " OK\n");
  console.log("  now land it:  .\\LAND.cmd     (message: \"RELAY 0.24 - the live lag, and no minimum breath\")\n");
} else {
  console.log("  MISMATCH   wrote " + back.length + "/" + next.length + " bytes . sha " +
              sha(back) + " vs " + WANT_SHA);
  console.log("  Send this to Glyph before landing anything.\n");
  process.exit(1);
}
