#!/usr/bin/env node
/* =============================================================================
   tools/apply_land_relay022.mjs — THE RECORD FOR RELAY 0.22
   run:  node tools\\apply_land_relay022.mjs

   Appends two entries to briefs/Session_Log.md:
     · 2026-08-26 -> 2026-09-05, RECONSTRUCTED from git evidence and labelled as
       such. It closes the gap in the record without pretending to be a memory.
     · 2026-09-08, RELAY 0.22 - the Vertebra session, Bill's verdict, the
       installer fault, and the open fork for 0.23.

   APPEND ONLY. It checks the file still ends where it expected before writing a
   byte, so it cannot clobber an entry added from another machine, and running it
   twice is a no-op rather than a duplicate.

   CANON.md is deliberately NOT touched. Section 4 is the post-summit CANDIDATE
   ledger and Relay was never one of those ten; the law's real registration is
   the `relay` entry in ZigCore.Canon.laws, which shipped inside zigcore.js.
   ========================================================================== */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";

const CANDIDATES = [
  path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."),
  process.cwd()
];
const looksRight = (d) => existsSync(path.join(d, "engine", "zigcore.js")) &&
                          existsSync(path.join(d, "briefs", "Session_Log.md"));
const ROOT = CANDIDATES.find(looksRight);
if (!ROOT) {
  console.log("\n  CANNOT LOCATE THE REPO. Tried:");
  CANDIDATES.forEach((d) => console.log("    " + d));
  console.log("  Run this from C:\\Users\\billy\\Zigverse - nothing was written.\n");
  process.exit(1);
}

const LOG    = path.join(ROOT, "briefs", "Session_Log.md");
const ENTRY  = Buffer.from('Ci0tLQoKIyMgMjAyNi0wOC0yNiDihpIgMjAyNi0wOS0wNSDCtyBSRUNPTlNUUlVDVEVEIElOIEFSUkVBUlMgKDIwMjYtMDktMDgpCgoqKlRoaXMgZW50cnkgaXMgcmVjb25zdHJ1Y3RlZCBmcm9tIGdpdCBldmlkZW5jZSwgbm90IGZyb20gYSByZWNvcmQga2VwdCBhdCB0aGUgdGltZS4qKiBJdCBleGlzdHMKc28gdGhlIGhpc3RvcnkgaXMgY29udGludW91cyByYXRoZXIgdGhhbiBhY2N1cmF0ZS1ieS1tZW1vcnkuIEFueXRoaW5nIG5vdCB2aXNpYmxlIGluIHRoZSByZXBvIGlzCm1hcmtlZCB1bmtub3duIHJhdGhlciB0aGFuIGd1ZXNzZWQuCgpUaGUgbG9nIHN0b3BwZWQgYXQgVE9VQ0ggQVMgQlJFQVRIICh2NC45KSBvbiAwOC0yNiB3aGlsZSB3b3JrIGNvbnRpbnVlZCBmb3IgYW5vdGhlciB0ZW4gZGF5cy4KV2hhdCB0aGUgbWlycm9yIGNhbiBwcm92ZToKCi0gKipDb21taXQgYDBkZjMzYzRgICJtb2JpbGUgcGFuZWwgZml4ICsgWmlnZ2xvdyB2MSIqKiAoMjAyNi0wOS0wNSksIHB1c2hlZCBgNWNmMDU3Yy4uMGRmMzNjNGAsCiAgMiBmaWxlcywgMTksNjk4IGluc2VydGlvbnMsIGJvdGggdW5kZXIgYGRpc3QvYDoKICBgZGlzdC9aaWd2ZXJzZV9FbmdpbmVfdjVfMV9JbnN0YWxsYWJsZV9tb2JpbGVmaXguaHRtbGAgYW5kIGBkaXN0L1ppZ2dsb3dfdjFfT2JzMV8zX21vYmlsZWZpeC5odG1sYC4KLSAqKlNvdXJjZSBpcyBub3Qgc3RyYW5kZWQuKiogVW5idW5kbGluZyB0aGUgdjUuMSBpbnN0YWxsYWJsZSBhbmQgZGlmZmluZyBhbGwgZml2ZSBtb2R1bGVzIGFnYWluc3QKICBgZW5naW5lL2AgYW5kIGBzcGVjaWVzL2AgcmV0dXJucyAqKjUvNSBJREVOVElDQUwqKiDigJQgYHppZ2NvcmUuanNgLCBgemlnd2ViZ3B1LmpzYCwgYHppZ21lc2guanNgLAogIGB6aWdtaWRpLmpzYCwgYHNpY2tsZXN3YXJtLmpzYC4gV2hhdGV2ZXIgd2FzIGJ1aWx0IGluIHRoZSBnYXAgcmVhY2hlZCBzb3VyY2UgYmVmb3JlIGl0IHNoaXBwZWQuCiAgVGhlICJ3b3JrIHN0cmFuZGVkIGluIGJ1bmRsZXMiIHJpc2sgZGlkICoqbm90KiogcmVjdXIuCgoqKlVua25vd24gLyBub3QgcmVjb3ZlcmFibGUgZnJvbSB0aGUgcmVwbzoqKiB3aGF0IHRoZSBtb2JpbGUgcGFuZWwgZmF1bHQgYWN0dWFsbHkgd2FzLCB3aGF0IFppZ2dsb3cKdjEgY2hhbmdlZCByZWxhdGl2ZSB0byB0aGUgZWFybGllciBaaWdnbG93IHdvcmssIGFuZCB3aGV0aGVyIHRoZSBgUGVyZi5iZW5kYCBsYWcgZmlsdGVyLCB0aGUKYHN0aWxsPWNhbG1gIGRlZmF1bHQsIG9yIHRoZSBgdmlld1s2OV1gIGRlYWQtd3JpdGUgZml4IHdlcmUgYW1vbmcgaXQuIFRob3NlIHJlbWFpbiBvcGVuIHVubGVzcwpCaWxsIHJlbWVtYmVycyBvdGhlcndpc2UuCgoqKkxlc3NvbiwgYW5kIGl0IGlzIHRoZSBzYW1lIG9uZSBhcyBiZWZvcmUgaW4gYSBuZXcgY29zdHVtZToqKiB0aGUgc291cmNlLW9mLXRydXRoIHJpc2sgd2FzIHNvbHZlZApmb3IgKmNvZGUqIGFuZCBsZWZ0IHVuc29sdmVkIGZvciAqcmVjb3JkKi4gQSBjb21taXQgcHJvdmVzIHdoYXQgY2hhbmdlZDsgb25seSB0aGUgbG9nIHNheXMgd2h5LgoKLS0tCgojIyAyMDI2LTA5LTA4IMK3IE9wdXMtR2x5cGggwrcgUkVMQVkgMC4yMiDigJQgdGhlIGVuZ2luZSBsZWFybnMgdGhhdCBhIGJvZHkgaGFzIGFuIE9SREVSCgoqKkFza2VkOioqIHRha2UgU2NvdXQncyBaSUdBTkFUT01JRVMgYnJpZWYgKEdpbGwgwrcgVmVydGVicmEgwrcgQ29jaGxlYSDCtyBBbHZlb2x1cykgYW5kIGFkZCB0aGUKY2hhcmFjdGVycyB0byB0aGUgZW5naW5lLiAiQW55IGlzc3Vlcz8iCgojIyMgVGhlIGZpbmRpbmcgdGhhdCByZXNoYXBlZCB0aGUgc2Vzc2lvbgoKUm91Z2hseSA3MCUgb2Ygd2hhdCBTY291dCdzIGJyaWVmIG5lZWRzIHdhcyAqKmFscmVhZHkgaW4gdGhlIGVuZ2luZSBhbmQgdW51c2VkKio6CgotICoqYFppZ0NvcmUuRXNjYXBlbWVudGAgMC4yMCoqIOKAlCByZWdpc3RlcmVkIGluIHRoZSBDYW5vbiBsZWRnZXIsIHByb3ZlbiBieSBgZXNjYXBlbWVudF9yZWZgLCBhbmQKICB3aXJlZCB0byAqKm5vdGhpbmcgYnV0IGBjbG9jay5odG1sYCoqLiBJdHMgb3duIGhlYWRlciBzdGF0ZXMgdGhhdCAqYSBjaGFpbiBvZiBzdGFnZXMgd2l0aAogIGRpZmZlcmVudCB0aHJlc2hvbGRzIGdlYXJzIGRvd24gZnJvbSBvbmUgc3VwcGx5Ki4gVGhhdCBpcyBWZXJ0ZWJyYSdzIHByb3BhZ2F0aW9uIGFuZCBBbHZlb2x1cydzCiAgc3RhZ2VkIHN1cnJlbmRlciwgYWxyZWFkeSB3cml0dGVuLgotICoqYFpJR0FHRWAgKHYwLjE1KSoqIOKAlCBgbGlmZUhhc2goaSlgIGFscmVhZHkgZ2l2ZXMgZXZlcnkgYWdlbnQgYSBwZXJzaXN0ZW50IGRldGVybWluaXN0aWMKICB2YXJpYXRpb24uIEdpbGwncyBoZWFsZWQgbm90Y2ggbmVlZHMgYSBuYW1lZCBkZWZlY3Qgc2xvdCwgbm90IGEgbmV3IHN5c3RlbS4KLSAqKkEgY29ycmVjdGlvbiB0byBhbiBlYXJsaWVyIGNsYWltIGluIHRoaXMgc2Vzc2lvbjoqKiBgWmlnV2ViR1BVLmNyZWF0ZU1lbWJyYW5lYCBpcyAqKmVsYXN0aWMKICBzcGFjZSwgbm90IGEgZHJhd24gc2tpbioqIOKAlCBhbiBpbnZpc2libGUgZmllbGQgc2hhcmRzIGluaGVyaXQgbG9jYWwgZ2VvbWV0cnkgZnJvbSAoYFpJR19TS0lOYCksCiAgcGx1cyBNSUNSTy1NRU1CUkFORSBsZXR0ZXJzIHRoYXQgc3dlbGwgYXMgZmlsbXMuIEluZmxhdGlvbiBwaHlzaWNzIGFuZCBicmVhdGhpbmcgZmlsbXM6IHllcy4KICBBIGNsb3NlZCB0cmFuc2x1Y2VudCBzYWMgd2l0aCBhIHZpc2libGUgaW50ZXJpb3I6ICoqbm8qKi4gVGhhdCByZW1haW5zIHRoZSBnZW51aW5lbHkgbmV3IGFuZAogIGV4cGVuc2l2ZSB0aGluZyBpbiBTY291dCdzIGJyaWVmLCBhbmQgaXQgd2FzIG92ZXJzb2xkIGJlZm9yZSB0aGUgc291cmNlIHdhcyByZWFkLgoKKipSdWxlZCBvdXQ6KiogZm91ciBtZXNoZXMgd2l0aCBNSURJIG1vZHVsYXRpb24gKFNjb3V0IHJ1bGVzIHRoaXMgb3V0IHRvbyk7IGZvcmtpbmcgdGhlIGVuZ2luZQooTWVyY2VkZXMgcHJpbmNpcGxlKS4KCiMjIyBCdWlsdCDigJQgYFppZ0NvcmUuUmVsYXlgIDAuMjIsICp3aGF0IGhhcHBlbnMgaGVyZSBoYXBwZW5zIHRoZXJlLCBsYXRlcioKCkVzY2FwZW1lbnQgdHVybnMgYSBjb250aW51b3VzIHN1cHBseSBpbnRvIGEgY291bnRhYmxlIGV2ZW50LiBJdCBzYXlzIG5vdGhpbmcgYWJvdXQgV0hFUkUsIGFuZCBhCnJhdyBjaGFpbiBmaXJlcyB0aGUgd2hvbGUgYm9keSBvbiAqKm9uZSBmcmFtZSoqIOKAlCBnZWFyaW5nIHdpdGggbm8gZ2VvZ3JhcGh5LiBSZWxheSdzIHNpbmdsZSBjaGFuZ2U6CmEgdGljayAqKnNjaGVkdWxlcyoqIHRoZSBuZXh0IHN0YWdlIGFmdGVyIGBsYWdgIHNlY29uZHMgaW5zdGVhZCBvZiBmaWxsaW5nIGl0LgoKLSAqKmBsYWdgKiog4oCUIHNlY29uZHMgcGVyIGhvcDsgdGhlIHdhdmUncyBzcGVlZC4gUGVyLXN0YWdlIGFycmF5IHN1cHBvcnRlZCAoc3RpZmYgbmVjaywgbG9vc2UgdGFpbCkuCi0gKipgZ2FpbmAqKiDigJQgZ2VhcmluZywgaW4gdW5pdHMgb2YgdGhlIGRvd25zdHJlYW0gdGhyZXNob2xkLiAxID0gZXZlcnkgZXZlbnQgdHJhdmVscyB0aGUgbGVuZ3RoLgotICoqYGJsZWVkYCoqIOKAlCBzdG9yZXMgbGVhayB0b3dhcmQgZW1wdHksIHNvIHRoZSBsYXN0IHdhdmUgZmluaXNoZXMgdHJhdmVsbGluZyAoKipmb2xsb3ctdGhyb3VnaCoqKQogIGFuZCB0aGVuIHRoZSBjaGFpbiBkZWNvbXByZXNzZXMgdG8gKipyZXN0KiogcmF0aGVyIHRoYW4gZnJlZXppbmcgbWlkLXBvc2UuCgpQdXJlIENQVSwgYnVpbHQgb24gRXNjYXBlbWVudCByYXRoZXIgdGhhbiBkdXBsaWNhdGluZyBpdC4gKipObyBzaGFkZXIgcGF0aCwgdGhlcmVmb3JlIG5vIE1ldGFsCmV4cG9zdXJlKiog4oCUIGJ5dGUtaWRlbnRpdHkgY29uZmlybXMgdGhlIFdHU0wgaXMgdW50b3VjaGVkLgoKKipGb3VuZCBieSB0aGUgcHJvb2YsIG5vdyBhbiBhc3NlcnRpb246KiogKmEgc3RvcmUgdGhhdCBsZWFrcyBjYW5ub3QgYWxzbyBjb3VudC4qIEdlYXJpbmcgbmVlZHMKY2hhcmdlIHRvIHN1cnZpdmUgdGhlIGdhcCBiZXR3ZWVuIGRlbGl2ZXJpZXM7IGJsZWVkIGRyYWlucyBpdC4gR2VhcmluZyBhbmQgYnJlYXRoaW5nIHRyYWRlIG9mZiwKKipwZXIgc3RhZ2UqKi4gQWxzbyByZWNvcmRlZDogYSByZWxheSBob3AgY29zdHMgKipvbmUgZnJhbWUgZXZlbiBhdCBsYWcgMCoqLCBzaW5jZSBhIGRlbGl2ZXJ5IGlzCmNvbnN1bWVkIHRoZSBmcmFtZSBhZnRlciBpdCBpcyBzY2hlZHVsZWQuCgojIyMgQmlsbCdzIHZlcmRpY3Qg4oCUIGp1ZGdlZCBnb29kCgo+ICoiVGhlIGRlbGF5IGlzIGNsZWFuIGNhdXNhdGlvbiDigJQgSSdsbCBzYXkgMC4xNywgYnV0IEkgdGhpbmsgdGhlIG1vdmVtZW50IHdvcmtzIGF0IGV2ZXJ5IGxhZwo+IHNldHRpbmcuIiogwrcgZ2FpbiAqInNob3VsZCBhbHdheXMgYmUgYXQgMSIqIMK3IGJsZWVkICoiaXMgc3VidGxlIHNvIEkgbmVlZCB0byBwbGF5IHdpdGggaXQuIioKCioqYGxhZ2AgMC4xNyBhbmQgYGdhaW5gIDEuMCBhcmUgdGhlIGp1ZGdlZCBkZWZhdWx0cy4qKiBUaGF0IHRoZSBtb3ZlbWVudCB3b3JrcyBhdCAqZXZlcnkqIGxhZyBpcwppdHNlbGYgdGhlIGZpbmRpbmc6IGlmIHRoZSBhYnNvbHV0ZSB2YWx1ZSBkb2Vzbid0IG11Y2ggbWF0dGVyLCBob2xkaW5nIGl0IGNvbnN0YW50IGlzIHRoZSB3YXN0ZS4KCiMjIyBUaGUgaW5zdGFsbGVyIGZhdWx0IOKAlCBhIG5ldyBnYXRlIGxlc3NvbgoKVGhlIGZpcnN0IGBhcHBseV92ZXJ0ZWJyYS5tanNgIHVzZWQgYG5ldyBVUkwoaW1wb3J0Lm1ldGEudXJsKS5wYXRobmFtZWAgdG8gZmluZCB0aGUgcmVwby4gT24KV2luZG93cyB0aGF0IHlpZWxkcyBgL0M6L1VzZXJzLy4uLmAsIGFuZCBqb2luaW5nIGl0IHByb2R1Y2VzICoqYEM6XEM6XFVzZXJzXC4uLmAqKi4gSXQgcGFzc2VkIG9uCnRoZSBMaW51eCBjb250YWluZXIgYW5kICoqY291bGQgbm90KiogcGFzcyBvbiBleWVaLiBGaXhlZCB3aXRoIGBmaWxlVVJMVG9QYXRoYCDigJQgYW5kIHRoZW4gbWFkZQpzdHJ1Y3R1cmFsOiAqKnRoZSBpbnN0YWxsZXIgbm93IFBST1ZFUyBpdHMgcm9vdCoqLCBhY2NlcHRpbmcgYSBjYW5kaWRhdGUgb25seSBpZiBgZW5naW5lL3ppZ2NvcmUuanNgLApgdGVzdC9gIGFuZCBgdG9vbHMvYCBhcmUgYWN0dWFsbHkgdGhlcmUsIGFuZCByZWZ1c2luZyB0byB3cml0ZSBhdCBhbGwgb3RoZXJ3aXNlLiBUZXN0ZWQgZnJvbSB0aGUKcmVwbyByb290LCBmcm9tIGFuIHVucmVsYXRlZCBjd2QsIGFuZCBmcm9tIGFuIGludmFsaWQgbG9jYXRpb24uCgoqVGhlIG1hY2hpbmUgdGhhdCB0ZXN0cyBpcyBub3QgdGhlIG1hY2hpbmUgdGhhdCBydW5zLiogU2FtZSBzaGFwZSBhcyB0aGUgTWV0YWwgbGVzc29uLgoKKipDaGFuZ2VkOioqIGBlbmdpbmUvemlnY29yZS5qc2AgKCtgWmlnQ29yZS5SZWxheWAsICtDYW5vbiBsZWRnZXIgZW50cnkgYHJlbGF5YCkgwrcgYGJyaWVmcy9TZXNzaW9uX0xvZy5tZGAKKipBZGRlZDoqKiBgdGVzdC92ZXJ0ZWJyYV9yZWYubWpzYCAoMjIgY2hlY2tzKSDCtyBgdG9vbHMvcmVsYXlfc2NvcGUuaHRtbGAgKGNhbnZhcy0yRCBsYXcgc2NvcGUsIG5vdAphbiBvcmdhbmlzbSwgbm90IHBhcnQgb2YgYW55IGJ1aWxkKSDCtyBgdG9vbHMvYXBwbHlfdmVydGVicmEubWpzYAoqKlBhc3NlZDoqKiBgbm9kZSAtLWNoZWNrYCBjbGVhbiAoNCBmaWxlcykgwrcgcmVmZXJlbmNlIGdhdGUgKio0My80MyoqICg0MiBpbmhlcml0ZWQgKyBgdmVydGVicmFfcmVmYCkgwrcKYnl0ZS1pZGVudGl0eSAqKjUvNSBJREVOVElDQUwqKiB2cyBgMGRmMzNjNGAgwrcgaW5zdGFsbGVyIHNlbGYtdmVyaWZ5LCAzLzMgc2hhMjU2IE9LIG9uIGV5ZVogwrcKTWV0YWwgZ2F0ZSAqKm5vdCBydW4qKiDigJQgYW5kICpub3QgcmVxdWlyZWQqOiBubyBXR1NMIGNoYW5nZWQuCgoqKk9wZW46KiogUmVsYXkgMC4yMyAobGFnIGRyaXZlbiBieSBub3RlLWNoYW5nZSBpbnRlcnZhbCwgYmVsb3cpIMK3IHRoZSBkcmF3bi1tZW1icmFuZSBwcmltaXRpdmUKZm9yIEdpbGwvQWx2ZW9sdXMsIHN0aWxsIHVuYnVpbHQgYW5kIHN0aWxsIHRoZSBleHBlbnNpdmUgaXRlbSDCtyBhIG5hbWVkIGRlZmVjdCBzbG90IG9uIGBaSUdBR0VgIMK3Cm5vIFZlcnRlYnJhICoqc3BlY2ltZW4qKiB5ZXQg4oCUIHRoZSBjYXBhYmlsaXR5IGlzIGluLCB0aGUgb3JnYW5pc20gdGhhdCBkcmF3cyBpdCBpcyBub3QgwrcKdmVyc2lvbiBzdGFtcHMgc3RpbGwgYFppZ1dlYkdQVS5WRVJTSU9OYCAwLjQ2LjAgwrcgYFppZ0NvcmUuU2Vzc2lvbmAuCgojIyMgTmV4dCDigJQgUmVsYXkgMC4yMywgbGFnIGZyb20gdGhlIHJhdGUgb2Ygbm90ZSBjaGFuZ2UKCkJpbGw6ICoidGhlIHRlbGVtZXRyeSB0aGF0IGZpdHMgbXkgcGxheWluZ+KApiBub3QgdG9uZ3Vpbmcgb3IgYnJlYXRoaW5nLCBqdXN0IHRoZSBleGFjdCB0aW1lIGVhY2gKbm90ZSBjaGFuZ2VzIHRvIHRoZSBuZXh0LiIqCgoqKmBaaWdDb3JlLlBhY2VtYWtlcmAgYWxyZWFkeSBtZWFzdXJlcyB0aGlzKiog4oCUIGV2ZXJ5IG5vdGUtb24gbGFuZHMgdGhlcmUsIGl0IGNvbXB1dGVzIGBpb2lgLAptYWludGFpbnMgYHBlcmlvZGAgYW5kIGBjb25maWRlbmNlYCwgYW5kIGhhcm1vbmljLXNuYXBzIHNvIGEgZG91YmxlLWxlbmd0aCBwaHJhc2UgcmVhZHMgYXMgdGhlCnBlcmZvcm1lcidzIHRlbXBvIHJhdGhlciB0aGFuIGhhbGYgb2YgaXQuIEJ1aWx0IGZyb20gQmlsbCdzIG93biB0ZWxlbWV0cnksIDIwMjYtMDctMTkuIFJlbGF5CnNob3VsZCAqKnJlYWQqKiBpdCwgbm90IGJ1aWxkIGEgc2Vjb25kIGVzdGltYXRvci4KCioqQ2FsaWJyYXRpb246KiogUGFjZW1ha2VyJ3MgcmVzdGluZyBgcGVyaW9kYCBpcyAwLjc1cy4gQXQgYHJhdGlvID0gMC4yMjdgLCBsYWcgbGFuZHMgb24gKipleGFjdGx5CkJpbGwncyBqdWRnZWQgMC4xNyoqIGF0IGhpcyByZXN0aW5nIG5vdGUgcmF0ZSDigJQgaGlzIGV5ZSBiZWNvbWVzIHRoZSBjb25zdGFudCB0aGUgbGF3IGlzIHNjYWxlZCBmcm9tLgoKKipUaGUgZnJlZSBjb25zZXF1ZW5jZToqKiBsYWcgaXMgcmVhZCBvbmx5IGF0IHRoZSBtb21lbnQgYSBzdGFnZSBzY2hlZHVsZXMgdGhlIG5leHQsIHNvIGEgZGVsaXZlcnkKYWxyZWFkeSB0cmF2ZWxsaW5nIGtlZXBzIHRoZSBsYWcgaXQgbGF1bmNoZWQgd2l0aC4gQWNjZWxlcmF0ZSwgYW5kIGEgZmFzdCB3YXZlIGxhdW5jaGVkIGJlaGluZCBhCnNsb3cgb25lICoqY2F0Y2hlcyB1cCB0byBpdCoqIOKAlCB0aGUgYm9keSBjb21wcmVzc2VzOyBkZWNlbGVyYXRlIGFuZCB0aGUgd2F2ZXMgc3ByZWFkLiBFbWVyZ2VudCwgbm90CnNjcmlwdGVkLCBhbmQgaXQgZXhpc3RzICpvbmx5KiBiZWNhdXNlIHRoZSBkcml2ZXIgaXMgcGVyLWV2ZW50IHJhdGhlciB0aGFuIGNvbnRpbnVvdXMuCgoqKk9wZW4gZGVzaWduIGZvcmsgZm9yIEJpbGw6KiogcmF3IGBpb2lgIChldmVyeSBmaW5nZXJpbmcgY2hhbmdlIG1vdmVzIHRoZSBsYWc7IGEgdHJpbGwgbWFrZXMgdGhlCmJvZHkgZnJhbnRpYykgdnMgUGFjZW1ha2VyJ3Mgc21vb3RoZWQgYHBlcmlvZGAgKHRoZSBib2R5IGxlYXJucyB0aGUgdGVtcG87IG9ybmFtZW50cyBkb24ndCBkaXN0dXJiCml0KS4gVG8gYmUgYnVpbHQgYXMgYSBgc25hcGAgYmxlbmQga25vYiBzbyBpdCBpcyBqdWRnZWQgbGl2ZSByYXRoZXIgdGhhbiBjaG9zZW4gYmxpbmQuCg==', "base64");
const ANCHOR = Buffer.from('YW4gc2xpbmdzaG90KSDCtyBgWmlnQ29yZS5TZXNzaW9uYCDCtyBMb2dpYyBQcm8gc291bmQgY2xlYW51cAphbmQgZ2xpdGNoIGZpeCBzdGlsbCB1bmxvZ2dlZCDCtyBSQy02MDAgKyBPQlMgc2Vzc2lvbiDCtyBgc3BsaWNlX2FuY2hvcnMubWpzYCBzdGFsZSBkZWZhdWx0IHBhdGguCg==', "base64");
const WANT_SHA = '1322a0275e69e24c';
const sha = (b) => createHash("sha256").update(b).digest("hex").slice(0, 16);

console.log("\n  ZIGVERSE - landing the record for RELAY 0.22\n  root: " + ROOT + "\n");

const cur = readFileSync(LOG);
if (cur.includes(ENTRY)) {
  console.log("  ALREADY PRESENT  briefs/Session_Log.md - nothing to do.\n");
  process.exit(0);
}
if (!cur.subarray(-ANCHOR.length).equals(ANCHOR)) {
  console.log("  REFUSING TO WRITE. briefs/Session_Log.md does not end where expected -");
  console.log("  something was appended since this installer was built. Nothing written;");
  console.log("  send this to Glyph and the entry will be rebuilt against the current file.\n");
  process.exit(1);
}

const next = Buffer.concat([cur, ENTRY]);
writeFileSync(LOG, next);
const back = readFileSync(LOG);
if (back.length === next.length && sha(back) === WANT_SHA) {
  console.log("  APPENDED   briefs/Session_Log.md   " + cur.length + " -> " + back.length +
              " bytes  (+" + ENTRY.length + ") . sha " + sha(back) + " OK\n");
  console.log("  now land it:  .\\LAND.cmd     (message: \"RELAY 0.22 - the body gains an order\")\n");
} else {
  console.log("  MISMATCH   wrote " + back.length + "/" + next.length + " bytes . sha " +
              sha(back) + " vs " + WANT_SHA);
  console.log("  Send this to Glyph before landing anything.\n");
  process.exit(1);
}
